version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo "Entered into pre-build phase"
    build:
      - echo "Entered into pre-build phase"
      - mvn clean install
  post_build:
    commands:
      - echo "Build completed"
artifacts:
  files:
    - '**/*'
  discard-paths: yes