version: 0.2
phases:
  pre_build:
    commands:
      - echo "Entered into pre-build phase"
    build:
      - echo "Entered into pre-build phase"
      - mvn clean install
  post_build:
    commands:
      - echo "Build completed"
artifacts:
  files:
    - secondService-0.0.1-SNAPSHOT.jar
  discard-paths: yes