spring:
  cloud:
    compatibility-verifier:
      enabled: false
  config:
    import: optional:configserver:http://localhost:8012


management:
  endpoints:
    web:
      exposure:
        include: refresh

server:
  port: 9009
