spring:
  cloud:
    compatibility-verifier:
      enabled: false
  config:
    import: "optional:configserver:http://localhost:8012"
    fail-fast: false

  devtools:
    add-properties: false

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: refresh

server:
  port: 8086

logging:
  level:
    web: 'DEBUG'