spring:
  profiles:
    active: test
  application:
    name: config-client
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      import: optional:configserver:http://localhost:8012
      enabled: false
      import-check: false

server:
  port: 9090
my: 9098
